version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.112
  proxy:
    image: nginx
    depends_on:
      - app
    volumes:
      - .:/var/www/html
      - ./docker/nginx_conf:/etc/nginx/conf.d/
    ports:
      - "8086:80"
  composer:
    image: composer
    volumes:
    - .:/app