version: "3.1"

services:
  app:
    build:
      context: ./php
    volumes:
      - ../:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    ports:
      - "3606:3306"

  proxy:
    image: nginx
    volumes:
      - ../:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8086:80"
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    ports:
      - "8087:80"

  composer:
    image: composer
    volumes:
    - ../:/app
